// Generated by Claude Sonnet 4 (claude-sonnet-4-20250514)
package com.formalcalculation.arithmetic

/** 比較演算子の共通実装を提供するトレイト */
trait ComparisonOps[A] {
  /** 比較メソッドの実装が必要 */
  protected def compare(other: A): Int
  
  /** 共通の比較演算子 */
  inline def <(other: A): Boolean = compare(other) < 0
  inline def <=(other: A): Boolean = compare(other) <= 0
  inline def >(other: A): Boolean = compare(other) > 0
  inline def >=(other: A): Boolean = compare(other) >= 0
}

/** 等価性演算子の共通実装を提供するトレイト */
trait EqualityOps[A] {
  /** 等価性メソッドの実装が必要 */
  protected def equal(other: A): Boolean
  
  /** 非等価性 */
  inline def notEqual(other: A): Boolean = !equal(other)
}