// Generated by Claude Sonnet 4 (claude-sonnet-4-20250514)
package com.formalcalculation.arithmetic.impl

import com.formalcalculation.arithmetic.{Integer, NonZeroInteger}

/** Option[NonZeroInteger]を使った整数の実装 */
final case class IntegerWrapper(option: Option[NonZeroInteger]) extends Integer {
  inline def toOption: Option[NonZeroInteger] = option
}

// 後方互換性のためのエイリアス
val IntegerZero: Integer = IntegerWrapper(None)
inline def IntegerPositive(value: com.formalcalculation.arithmetic.Natural): Integer = 
  IntegerWrapper(Some(NonZeroInteger.fromNatural(value)))
inline def IntegerNegative(value: com.formalcalculation.arithmetic.Natural): Integer = 
  IntegerWrapper(Some(NonZeroInteger.Negative(value)))