// Generated by Claude Sonnet 4 (claude-sonnet-4-20250514)
package com.formalcalculation.arithmetic.impl

import com.formalcalculation.arithmetic.{Rational, Integer, NonZeroInteger}

/** 有理数の実装 */
final case class RationalWrapper(numerator: Integer, denominator: NonZeroInteger) extends Rational