# GitHub Actions workflow for Scala Steward
# https://github.com/scala-steward-org/scala-steward-action

name: Scala Steward

on:
  schedule:
    # Run every Sunday at 03:00 UTC
    - cron: '0 3 * * 0'
  workflow_dispatch: # Allow manual triggering

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Scala Steward
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          repos-file: 'repos.md'
          github-token: ${{ steps.generate_token.outputs.token }}
          author-email: 'me@formalcalculation.com'
          author-name: 'Scala Steward'
          sign-commits: true
          cache-ttl: '24hours'